spring:
  kafka:
      bootstrap-servers: 192.168.94.128:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        group-id: test
        enable-auto-commit: true
        auto-commit-interval: 1000
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
       mysql:
          jdbc-url: jdbc:mysql://localhost:3306/system_demo?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
          username: root
          password: 563102
          driver-class-name: com.mysql.cj.jdbc.Driver
          connection-timeout: 60000
  redis:
    host: 192.168.94.128
    port: 6379
    password: 563102
    database: 0
    timeout: 5000
mybatis:
  mapperLocations: classpath*:com/**/mapper/*.xml
# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
server:
  port: 8000
logging:
  file:
    path: d:\\temp\logs
  level:
    root: info
    org:
      springframework:
        web: DEBUG
    com.cet.diagsyscloud.system.dao: DEBUG
